# Generated by Django 5.2 on 2025-04-06 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazarus', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.TextField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('jobtype', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('appliedusers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
