# Generated by Django 5.2 on 2025-04-06 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazarus', '0004_skill_user_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='jobtitle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='lazarus.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lazarus.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
