# Generated by Django 5.2 on 2025-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazarus', '0005_rename_jobtitle_jobposting_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
