# Generated by Django 5.2 on 2025-04-12 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazarus', '0006_alter_jobposting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='appliedusers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
